### ISSUE TITLE
WorkShop

### ISSUE THREAD

**Issue by chanceous** [Net-Baires/charlas#1]
### Título
Workshop Sobre Creacion de Sitios Web con App Service y PHP en Azure

### Descripción
Basicamente Enseñare a Crear Sitios Web en App Service con la Ayuda Azure y de una Plantilla que Estoy Preparando en PHP 

### Sobre el orador
**Twitter:** @chrischance67

**Sitio:** www.christopherwebdeveloper.hol.es

### Recursos
**Slides de la presentación:** Aun No

**Repositorio de la charla:** Aun No

### Extra
Tenes la charla preparada?
Casi
En qué mes la podrías dar?
Cualquiera
Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
Azure Pass y que Todos Tengan Visual Studio Code

**Comment by sebaleoperez** [comment]
Estoy revisando las propuestas, si aún estás interesado Chris en hacer este Workshop completa este formulario:

https://bit.ly/speakernetbaires

Saludos !
