### ISSUE TITLE
Charla: Embelleciendo nuestras aplicaciones ASP.NET MVC

### ISSUE THREAD

**Issue by ignacioinnovo** [Net-Baires/charlas#2]
### Título
Embelleciendo nuestras aplicaciones ASP.NET MVC

### Descripción
Utilizaremos un framework gratuito de última generación basado en Bootstrap y con pilares de Material Design para que nuestras aplicaciones web se luzcan.

### Sobre el orador
Sitio: www.innovotecnologias.com.ar

### Recursos
No la tengo subida pero casi lista la presentación. Les dejo, igualmente, los artículos que escribí en el sitio oficial del framework y en Medium:

https://mdbootstrap.com/articles/miscellaneous/mdbootstrap-on-asp-net-mvc

https://mdbootstrap.com/articles/miscellaneous/ready-to-use-asp-net-mvc-templates-from-mdb-and-how-to-integrate-them/

https://medium.com/@innovotecnologias/plantillas-de-mdbootstrap-listas-para-usar-y-c%C3%B3mo-hacer-la-integraci%C3%B3n-con-asp-net-mvc-ee33f8c8975d

En el primer repositorio está la base de la charla y en los otros son plantillas listas para usar

https://github.com/InnovoTecnologias/MDBinASP.NET
https://github.com/InnovoTecnologias/MDBBlog
https://github.com/InnovoTecnologias/MDBTwoColumnsListing
https://github.com/InnovoTecnologias/MDBSaas
https://github.com/InnovoTecnologias/MDBPortfolio
https://github.com/InnovoTecnologias/MDBOneColumnListing
https://github.com/InnovoTecnologias/MDBLandingPage
https://github.com/InnovoTecnologias/MDBEcommerce
https://github.com/InnovoTecnologias/MDBDashboard
https://github.com/InnovoTecnologias/MDBComingSoon
https://github.com/InnovoTecnologias/MDBFullPageImage
https://github.com/InnovoTecnologias/MDBFullPageImageCarousel
https://github.com/InnovoTecnologias/MDBMagazine
https://github.com/InnovoTecnologias/MDBFullPageVideoCarousel
https://github.com/InnovoTecnologias/MDBHalfPageImageCarousel
https://github.com/InnovoTecnologias/MDBLandingPage

### Extra
Tenes la charla preparada? Sí. Debo terminar detalles solamente.

En qué mes la podrías dar?
No tengo inconvenientes si es que arreglamos con tiempo.

**Comment by soydiloreto** [comment]
Gracias @ignacioinnovo ! Lo evaluamos y seguimos contacto.

**Comment by sebaleoperez** [comment]
Ya fue realizada ! Muchas gracias Ignacio !

**Comment by ignacioinnovo** [comment]
Gracias a ustedes! Me sentí muy cómodo. NetBaires es una comunidad excelente! Entre otras cosas, gracias a sus organizadores @pablodiloreto , @sebaleoperez  y @germankuber !
